version: '3.2'

services:
  teamcity-server:
    image: jetbrains/teamcity-server
    ports:
      - 8111:8111
    volumes:
      - ./data_dir:/data/teamcity_server/datadir
      - ./log_dir:/opt/teamcity/logs
  teamcity-agent:
    image: jetbrains/teamcity-agent
    environment:
      - SERVER_URL=http://teamcity-server:8111
      - TEAMCITY_SERVER_MEM_OPTS=-Xmx2g -XX:ReservedCodeCacheSize=350m
      - DOCKER_IN_DOCKER=start
      - DOCKER_OPTS=--insecure-registry docker-registry:5000
      - DOCKER_HOST=tcp://localhost:2375
    privileged: true
    volumes:
      - docker_volumes:/var/lib/docker
  docker-registry:
    image: registry:2
    ports:
      - 5000:5000

volumes:
  docker_volumes:
